### ISSUE TITLE
Question: sdist validation?

### ISSUE THREAD

**Issue by AstraLuma** [di/calver#2]
Is using this package different from just doing:

```
setup(
    # ...
    version=time.strftime('%Y.%m.%d.%H.%M', time.gmtime()),
    # ...
)
```

The reason I ask is that at $DAYJOB, I'm having trouble with that version of auto-calver and pip:

```
WARNING: Discarding https://<url>/mypkg-2020.10.15.13.52.tar.gz#sha256=<sha> (from https://<url>/+simple/mypkg/). Requested mypkg from https://<url>/mypkg-2020.10.15.13.52.tar.gz#sha256=<sha> (from -r requirements.txt (line 33)) has inconsistent version: filename has '2020.10.15.13.52', but metadata has '2021.1.29.16.52'
```

I assume this is because the version number is not a "pure" function (at least with respect to the sdist), but potentially changes every time you interrogate the sdist for metadata.

**Comment by di** [comment]
It's not different, this library has the same effect on packages that use it when installing from a source distribution:

```
$ docker run -it python bash
root@2424c24a316c:/# python -m pip install https://files.pythonhosted.org/packages/6e/30/60a54184e9d084c7e036426ee9465cdbfa46d5a77d77c407dcba1c2c9e2f/trove-classifiers-2021.1.14.tar.gz
Collecting https://files.pythonhosted.org/packages/6e/30/60a54184e9d084c7e036426ee9465cdbfa46d5a77d77c407dcba1c2c9e2f/trove-classifiers-2021.1.14.tar.gz
  Downloading trove-classifiers-2021.1.14.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: trove-classifiers
  Building wheel for trove-classifiers (PEP 517) ... done
  Created wheel for trove-classifiers: filename=trove_classifiers-2021.2.3-py3-none-any.whl size=8209 sha256=af9de8b27c7633fd5b5e5eac9148f8ad9be525139a25bc9d3dbd07d4db31db12
  Stored in directory: /root/.cache/pip/wheels/eb/08/68/c8cc06e77deae7992726ba120e8c608b51d40d895851f00d74
Successfully built trove-classifiers
Installing collected packages: trove-classifiers
Successfully installed trove-classifiers-2021.2.3
```

**Comment by AstraLuma** [comment]
to be clear: I've only been able to trigger that error when using version resolution, not specific files.

**Comment by di** [comment]
Sorry, not sure I follow. That error will happen when `pip` tries to install a specific version of a source distribution: if the version is dynamic, it will produce a different installed version than `pip` was expecting. This is true for any source distribution with a dynamic version.

**Comment by AstraLuma** [comment]
I set up a project to demonstrate: [GitHub](https://github.com/AstraLuma/a-calver-test) [PyPI](https://pypi.org/project/a-calver-test/)

There's two important aspects to this phenomenon:
* The version number in `setup.py` is always the current date/time
* Wheels are not produced/uploaded, just sdists

This results in:

```
$ pip install a-calver-test
Collecting a-calver-test
  Downloading a-calver-test-2021.2.3.19.28.tar.gz (1.1 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/5a/cb/da3ee0b41deccc6f47829c17996d8c41da1fa9b2eff51cf1268ca9d4b7ce/a-calver-test-2021.2.3.19.28.tar.gz#sha256=1c97c824cc30d4b72ba54aa47faf1c9f6320489ff3ab30195931b8e1a4a3ac1f (from https://pypi.org/simple/a-calver-test/). Requested a-calver-test from https://files.pythonhosted.org/packages/5a/cb/da3ee0b41deccc6f47829c17996d8c41da1fa9b2eff51cf1268ca9d4b7ce/a-calver-test-2021.2.3.19.28.tar.gz#sha256=1c97c824cc30d4b72ba54aa47faf1c9f6320489ff3ab30195931b8e1a4a3ac1f has inconsistent version: filename has '2021.2.3.19.28', but metadata has '2021.2.4.15.21'
ERROR: Could not find a version that satisfies the requirement a-calver-test
ERROR: No matching distribution found for a-calver-test
```

Note that this does not happen if you use a local file or a precise URL. You have to refer to the package by name, to be automatically found and downloaded.

**Comment by AstraLuma** [comment]
my thought for fixing this (besides uploading wheels, because there's situations where pip won't select the wheel) is to insert some kind of version file into the sdist at package time, so that if you work from an sdist, it will have the same version as at the time of packaging. But if you work from a git checkout, it'll produce new versions.
